Day7pt1 iss#01
Cobra915/AdventOfCode2022 pull request #2
Opened 2022-12-26 22:42 UTC by Cobra915

got it finished. 

I tried adding some code to display_output that would write the File_Tree dict to a JSON or txt documents but I couldn't get it working.

2022-12-28 18:15 UTC, Mietzsche81 commented
@Cobra915 There are some binary `.pyc` files that should be deleted too.

2022-12-28 18:15 UTC, Mietzsche81 requested changes

2022-12-28 18:15 UTC, Mietzsche81 commented on python/Test_Space.py
> -import os
Don't commit test space to your repo. These are temporary files.

2022-12-28 18:15 UTC, Mietzsche81 commented on python/day7/convert.txt
> +localfiles
Is this example output? If so, don't commit it.

2022-12-28 18:15 UTC, Mietzsche81 commented on python/day7/day7part1/__main__.py
> +    File_Tree = build.build_file_tree(data)
`File_Tree` -> `file_tree`

https://pep8.org/#naming-conventions

2022-12-28 18:15 UTC, Mietzsche81 commented on python/day7/day7part1/__main__.py
> +    R_List = transform.find_small_directories(File_Tree)
Delete commented code?

2022-12-28 18:15 UTC, Mietzsche81 commented on python/day7/day7part1/display_output.py
> +    # print(f"The filesystem was written to {convert_file}")
Delete commented code

2022-12-28 18:15 UTC, Mietzsche81 commented on python/day7/day7part1/display_output.py
> +import json
Delete unused imports

2023-01-11 17:51 UTC, Cobra915 reviewed
Commented changes made

2023-01-15 21:40 UTC, Mietzsche81 approved these changes

2023-01-15 21:40 UTC, merged